FROM danijel3/clarin-pl-speechmodels:sejm
MAINTAINER Danijel Koržinek <danijel@pja.edu.pl>

RUN ln -s /usr/bin/python3 /usr/bin/python

COPY parse_options.sh /parse_options.sh

RUN python -m pip install textgrid

RUN apt-get update && \
    apt-get install -y bc && \
    apt-get clean && apt-get autoclean && rm -rf /var/lib/apt/lists/*

COPY dist /dist

COPY tools /tools

ENTRYPOINT ["/bin/bash","-c"]